[game]
name = "Dyson Sphere Program" # 游戏名称
name-zh-cn = "戴森球计划" # 游戏名称中文
platform = "win10" # 运行平台：win10 linux mac android ios win7 winxp ns
path = 'unknown' # 游戏路径
exe_path = 'unknown' # 运行文件相对路径
save_path = 'D:\Files\Documents\Dyson Sphere Program\Blueprint\自用' # 存档文件相对路径
save_latest = false

[base]
download = "steam" # steam，或下载地址/页面
