[game]
name = "Sekio" # 游戏名称
name-zh-cn = "只狼" # 游戏名称中文
platform = "win10" # 运行平台：win10 linux mac android ios win7 winxp ns
path = 'C:\Apps\Steam\steamapps\common\Sekiro' # 游戏路径
exe_path = 'C:\Apps\Steam\steamapps\common\Sekiro\sekiro.exe' # 运行文件相对路径
save_path = 'C:\Users\chenxi-zqs\AppData\Roaming\Sekiro\76561198876586946' # 存档文件相对路径
save_latest = false

[base]
download = "steam" # steam，或下载地址/页面
