[game]
name = "BLUE PRINCE" # 游戏名称
name-zh-cn = "蓝途王子" # 游戏名称中文
platform = "win10" # 运行平台：win10 linux mac android ios win7 winxp ns
path = 'C:\Games\Blue Prince' # 游戏路径
exe_path = 'C:\Games\Blue Prince\Blue Prince\BLUE PRINCE.exe' # 运行文件相对路径
save_path = 'C:\Users\chenxi-zqs\AppData\LocalLow\Dogubomb\BLUE PRINCE\storage' # 存档文件相对路径
save_latest = false

[base]
download = "steam" # steam，或下载地址/页面
